name = "rumah-bucin"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "rumah_bucin_db"
database_id = "13e4b086-2e94-4912-aaf9-565d6c9b2c01"

[[r2_buckets]]
binding = "FILES"
bucket_name = "rumah-bucin-files"
